### ISSUE TITLE
I would like the ability to manage the MS device management interfaces

### ISSUE THREAD

**Issue by richardjohnallsopp** [CiscoDevNet/ansible-meraki#207]
Currently the following only works for MX devices - https://n314.meraki.com/Wireless-Templat/n/6TZSfbs/manage/support/api_docs/v1#management-interface-settings

What's super annoying is that you can query the management interface on a switch, but you can't set it.
```
    - name: set vlan on management information
      meraki_management_interface:
        auth_key: "{{ auth_key }}"
        org_name: "{{  org_name  }}"
        net_name: "{{  network_name  }}"
        state: "present"
        serial: "{{  ms_serial  }}"
        wan1:
          wan_enabled: "enabled"
          using_static_ip: false
          vlan: "30"
      delegate_to: localhost
      register: man_info
      tags:
        - "query_man"
        - "setup_switch"        

    - name: query management information
      meraki_management_interface:
        auth_key: "{{ auth_key }}"
        org_name: "{{  org_name  }}"
        net_name: "{{  network_name  }}"
        state: "query"
        serial: "{{  ms_serial  }}"
      delegate_to: localhost
      register: man_info
      tags:
        - "query_man"
        - "setup_switch"

    - debug: msg="{{  man_info  }}"
      tags:
        - "query_man"
```
Output
```
TASK [set vlan on management information] ***************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => changed=false 
  msg: 'Unsupported parameters for (meraki_management_interface) module: man1 Supported parameters include: auth_key, host, internal_error_retry_time, net_id, net_name, org_id, org_name, output_format, output_level, rate_limit_retry_time, serial, state, timeout, use_https, use_proxy, validate_certs, wan1, wan2'

PLAY RECAP **********************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

(ansible-silverpeak) flynn@NCL-WL-16612:~/ansible-silverpeak/ansible$ ./configure_meraki_switch.sh -e site_code="f-pascu" --tags "query_man"

PLAY [all] **********************************************************************************************************************************************

TASK [set vlan on management information] ***************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not subscriptable
fatal: [localhost -> localhost]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/flynn/.ansible/tmp/ansible-tmp-1604013886.165115-173013334994219/AnsiballZ_meraki_management_interface.py", line 102, in <module>
        _ansiballz_main()
      File "/home/flynn/.ansible/tmp/ansible-tmp-1604013886.165115-173013334994219/AnsiballZ_meraki_management_interface.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/flynn/.ansible/tmp/ansible-tmp-1604013886.165115-173013334994219/AnsiballZ_meraki_management_interface.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.cisco.meraki.plugins.modules.meraki_management_interface', init_globals=None, run_name='__main__', alter_sys=False)
      File "/home/flynn/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line 208, in run_module
        return _run_code(code, {}, init_globals, run_name, mod_spec)
      File "/home/flynn/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_meraki_management_interface_payload_3u_uwcj4/ansible_meraki_management_interface_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_management_interface.py", line 369, in <module>
      File "/tmp/ansible_meraki_management_interface_payload_3u_uwcj4/ansible_meraki_management_interface_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_management_interface.py", line 356, in main
    TypeError: 'NoneType' object is not subscriptable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```
Query output
```
TASK [query management information] *********************************************************************************************************************
ok: [localhost -> localhost]

TASK [debug] ********************************************************************************************************************************************
ok: [localhost] => 
  msg:
    changed: false
    data:
      wan1:
        using_static_ip: false
        vlan: 30
    failed: false
    response: OK (unknown bytes)
    status: 200
```
I feel like it would be so easy for them to enable it for switches too.

**Comment by kbreit** [comment]
Something about that output is curious. It refers to `man1` but I don't see that phrase in the playbook. Any ideas why?

**Comment by richardjohnallsopp** [comment]
Sorry that was me trying to man instead of wan on the MS devices, it errors with noneType if you try wan.

**Comment by kbreit** [comment]
I am looking into it and am not able to reproduce your bug. I have an MS setup in a test network and am able to configure `wan1`. Are you able to send me a `debug` from a `state: query` task before and after that change? If you need to send privately, let me know.

**Comment by richardjohnallsopp** [comment]
Sure:

Tasks:
```
- name: configure management interface
      meraki_management_interface:
        auth_key: "{{ auth_key }}"
        org_name: "{{  org_name  }}"
        net_name: "{{  network_name  }}"
        state: "present"
        serial: "{{  ms_serial  }}"
        wan1:
          wan_enabled: "enabled"
          using_static_ip: false
          vlan: "30"
      delegate_to: localhost
      register: man_info
      ignore_errors: true
      tags:
        - "query_man"
        - "setup_switch"

    - name: query management information
      meraki_management_interface:
        auth_key: "{{ auth_key }}"
        org_name: "{{  org_name  }}"
        net_name: "{{  network_name  }}"
        state: "query"
        serial: "{{  ms_serial  }}"
      delegate_to: localhost
      register: man_info
      tags:
        - "query_man"
        - "setup_switch"

    - debug: msg="{{  man_info  }}"
      tags:
        - "query_man"
```
Output:

```
PLAY [all] ***************************************************************************************************************************************

TASK [configure management interface] ************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not subscriptable
fatal: [localhost -> localhost]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/flynn/.ansible/tmp/ansible-tmp-1604270379.8193467-27066047151014/AnsiballZ_meraki_management_interface.py", line 102, in <module>
        _ansiballz_main()
      File "/home/flynn/.ansible/tmp/ansible-tmp-1604270379.8193467-27066047151014/AnsiballZ_meraki_management_interface.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/flynn/.ansible/tmp/ansible-tmp-1604270379.8193467-27066047151014/AnsiballZ_meraki_management_interface.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.cisco.meraki.plugins.modules.meraki_management_interface', init_globals=None, run_name='__main__', alter_sys=False)
      File "/home/flynn/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line 208, in run_module
        return _run_code(code, {}, init_globals, run_name, mod_spec)
      File "/home/flynn/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_meraki_management_interface_payload_lvlnqgj4/ansible_meraki_management_interface_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_management_interface.py", line 369, in <module>
      File "/tmp/ansible_meraki_management_interface_payload_lvlnqgj4/ansible_meraki_management_interface_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_management_interface.py", line 356, in main
    TypeError: 'NoneType' object is not subscriptable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
...ignoring

TASK [query management information] **************************************************************************************************************
ok: [localhost -> localhost]

TASK [debug] *************************************************************************************************************************************
ok: [localhost] => 
  msg:
    changed: false
    data:
      wan1:
        using_static_ip: false
        vlan: 30
    failed: false
    response: OK (unknown bytes)
    status: 200

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1  
```

**Comment by richardjohnallsopp** [comment]
If you need the full debug let me know how to send it privately as it had sensitive data in it.

**Comment by kbreit** [comment]
Are you specifying `--diff` anywhere?

**Comment by richardjohnallsopp** [comment]
nope, nowhere in that or any other task

**Comment by richardjohnallsopp** [comment]
What does your task look like without the vaules?

**Comment by kbreit** [comment]
Here are the integration tests I'm running. What it seems like is yours is crashing when it generates a diff because there is no `before`. Your request is returning HTTP code 200 (based on the execution flow at least). I don't have a check whether diff is enabled or not so that could be a workaround but not a fix.

```
  - name: Set management interface on switch to not configured
    meraki_management_interface:
      auth_key: '{{auth_key}}'
      state: present
      org_id: '{{test_org_id}}'
      net_id: '{{test_switch_net_name}}'
      serial: '{{serial_switch}}'
      wan1:
        wan_enabled: not configured
    delegate_to: localhost
    register: ms_not_configured
    check_mode: yes
    diff: yes

  - debug:
      var: ms_not_configured

  - assert:
      that:
        - ms_not_configured.data is defined

  - name: Set management interface on switch
    meraki_management_interface:
      auth_key: '{{auth_key}}'
      state: present
      org_id: '{{test_org_id}}'
      net_id: '{{test_switch_net_name}}'
      serial: '{{serial_switch}}'
      wan1:
        wan_enabled: enabled
        using_static_ip: no
        vlan: 3
    delegate_to: localhost
    register: set_switch_mgmt
    check_mode: yes
    diff: yes

  - debug:
      var: set_switch_mgmt

  - assert:
      that:
        - set_switch_mgmt.data is defined

  - name: Query non-MX network
    meraki_management_interface:
      auth_key: '{{auth_key}}'
      state: query
      org_id: '{{test_org_id}}'
      net_id: '{{test_switch_net_name}}'
      serial: '{{serial_switch}}'
    delegate_to: localhost
    register: non_mx_network
    check_mode: yes

  - debug:
      var: non_mx_network

  - assert:
      that:
        - non_mx_network.data is defined

  - name: Reset management interface on switch
    meraki_management_interface:
      auth_key: '{{auth_key}}'
      state: present
      org_id: '{{test_org_id}}'
      net_id: '{{test_switch_net_name}}'
      serial: '{{serial_switch}}'
      wan1:
        wan_enabled: enabled
        using_static_ip: no
        vlan: 1
    delegate_to: localhost
    register: reset_switch_mgmt
    check_mode: yes
    diff: yes

  - debug:
      var: reset_switch_mgmt

  - assert:
      that:
        - reset_switch_mgmt.data is defined

  - meta: end_play
```

**Comment by kbreit** [comment]
Good news. I was able to reproduce the crash.

Bad news. I'm not entirely sure how to fix it and have a question into the Meraki team asking about a condition. The `wan_enabled` key isn't always returned. When it's not, it thinks it needs to do a change. However, I can't ignore that key altogether since it may break if you wanted to just enable it.

**Comment by richardjohnallsopp** [comment]
Right understood, I added the check mode and the diff options and it does seem to succeed, but doesn't when check mode is disabled.
```
PLAY [all] *********************************************************************************************************************************************************

TASK [configure management interface] ******************************************************************************************************************************
--- before
+++ after
@@ -1 +1,2 @@
-wan1: {}
+wan1:
+  wan_enabled: enabled

changed: [localhost -> localhost]

TASK [query management information] ********************************************************************************************************************************
ok: [localhost -> localhost]

TASK [debug] *******************************************************************************************************************************************************
ok: [localhost] => 
  msg:
    changed: false
    data:
      wan1:
        using_static_ip: false
        vlan: 30
    failed: false
    response: OK (unknown bytes)
    status: 200

PLAY RECAP *********************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by kbreit** [comment]
@richardjohnallsopp Please test the code in #208. Let me know if you have any questions. In short, `wan_enabled` shouldn't be provided for non-MX devices. In case you do, I added some logic which should ignore it.

**Comment by richardjohnallsopp** [comment]
Can I just pull this file to my local version?
`plugins/modules/meraki_management_interface.py`

**Comment by kbreit** [comment]
You should be able to? If it works, let me know and I can do a new release.

**Comment by richardjohnallsopp** [comment]
Works using the same code I posed above, nice job man :-)
