### ISSUE TITLE
Adding Static Routes using Ansible Meraki modules - Issues 

### ISSUE THREAD

**Issue by adarcy42** [CiscoDevNet/ansible-meraki#299]
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_meraki_static_route_payload__21s1zke/ansible_meraki_static_route_payload.zip/ansible/module_utils/network/meraki/meraki.py", line 92, in inner
ansible.module_utils.network.meraki.meraki.HTTPError: HTTP error 404 - None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adarcy/.ansible/tmp/ansible-tmp-1649264780.346914-30111-41099823046394/AnsiballZ_meraki_static_route.py", line 102, in <module>
    _ansiballz_main()
  File "/home/adarcy/.ansible/tmp/ansible-tmp-1649264780.346914-30111-41099823046394/AnsiballZ_meraki_static_route.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/adarcy/.ansible/tmp/ansible-tmp-1649264780.346914-30111-41099823046394/AnsiballZ_meraki_static_route.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.meraki.meraki_static_route', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_meraki_static_route_payload__21s1zke/ansible_meraki_static_route_payload.zip/ansible/modules/network/meraki/meraki_static_route.py", line 375, in <module>
  File "/tmp/ansible_meraki_static_route_payload__21s1zke/ansible_meraki_static_route_payload.zip/ansible/modules/network/meraki/meraki_static_route.py", line 320, in main
  File "/tmp/ansible_meraki_static_route_payload__21s1zke/ansible_meraki_static_route_payload.zip/ansible/module_utils/network/meraki/meraki.py", line 309, in get_nets
  File "/tmp/ansible_meraki_static_route_payload__21s1zke/ansible_meraki_static_route_payload.zip/ansible/module_utils/network/meraki/meraki.py", line 116, in inner
ansible.module_utils.network.meraki.meraki.HTTPError: HTTP error 404 - None
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_meraki_static_route_payload__21s1zke/ansible_meraki_static_route_payload.zip/ansible/module_utils/network/meraki/meraki.py\", line 92, in inner\nansible.module_utils.network.meraki.meraki.HTTPError: HTTP error 404 - None\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/adarcy/.ansible/tmp/ansible-tmp-1649264780.346914-30111-41099823046394/AnsiballZ_meraki_static_route.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/adarcy/.ansible/tmp/ansible-tmp-1649264780.346914-30111-41099823046394/AnsiballZ_meraki_static_route.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/adarcy/.ansible/tmp/ansible-tmp-1649264780.346914-30111-41099823046394/AnsiballZ_meraki_static_route.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.meraki.meraki_static_route', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_meraki_static_route_payload__21s1zke/ansible_meraki_static_route_payload.zip/ansible/modules/network/meraki/meraki_static_route.py\", line 375, in <module>\n  File \"/tmp/ansible_meraki_static_route_payload__21s1zke/ansible_meraki_static_route_payload.zip/ansible/modules/network/meraki/meraki_static_route.py\", line 320, in main\n  File \"/tmp/ansible_meraki_static_route_payload__21s1zke/ansible_meraki_static_route_payload.zip/ansible/module_utils/network/meraki/meraki.py\", line 309, in get_nets\n  File \"/tmp/ansible_meraki_static_route_payload__21s1zke/ansible_meraki_static_route_payload.zip/ansible/module_utils/network/meraki/meraki.py\", line 116, in inner\nansible.module_utils.network.meraki.meraki.HTTPError: HTTP error 404 - None\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1

**Comment by adarcy42** [comment]
Playbook, API and Org_Id have been removed but have both been checked and are correct. 

---

- name: Create Static Route on Meraki Device  
  hosts: localhost 
  connection: local 

  tasks: 

    - name: Add Route   
      meraki_static_route:
        auth_key: XXXX
        state: present
        org_id: XXXX
        net_name: SD-WAN LAB
        name: Ansible_Route 
        subnet: 10.223.10.0/24
        gateway_ip: 10.61.0.3
      delegate_to: localhost
