### ISSUE TITLE
setting hostname via ansible not working (meraki_device)

### ISSUE THREAD

**Issue by petertavenier** [CiscoDevNet/ansible-meraki#98]
When device is already in the network and I'm running this code to add a device to the network it's WORKING fine; 
```- name: Add a device(s) to a network
  meraki_device:
    auth_key: "{{ MERAKI_API_KEY }}"
    org_id: "{{ meraki_org_id }}"
    state: present
    net_name: "{{ net_name }}"
    serial: "{{ serial }}"
```

but when adding hostname it FAILS!
```- name: Add a device(s) to a network
  meraki_device:
    auth_key: "{{ MERAKI_API_KEY }}"
    org_id: "{{ meraki_org_id }}"
    state: present
    net_name: "{{ net_name }}"
    serial: "{{ serial }}"
    hostname: "{{ hostname }}"
```

but when I add tags instead of hostname it WORKS again, but tags are not added; (changed = false)
```- name: Add a device(s) to a network
  meraki_device:
    auth_key: "{{ MERAKI_API_KEY }}"
    org_id: "{{ meraki_org_id }}"
    state: present
    net_name: "{{ net_name }}"
    serial: "{{ serial }}"
    tags: "Ansible-managed"
```

updating device with code with hostname in it; FAILS
```- name: Update device(s) 
  meraki_device:
    auth_key: "{{ MERAKI_API_KEY }}"
    org_id: "{{ meraki_org_id }}"
    state: present
    net_name: "{{ net_name }}"
    serial: "{{ serial }}"
    hostname: "{{ hostname }}"
```

but with code, it works (no fail, but ansible doesn't change anything.. 
```- name: Update device(s) 
  meraki_device:
    auth_key: "{{ MERAKI_API_KEY }}"
    org_id: "{{ meraki_org_id }}"
    state: present
    net_id: "{{ net_id }}"
    serial: "{{ serial }}"
    hostname: "{{ hostname }}"
```

**Comment by petertavenier** [comment]
might be useful to add the error; 
```The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_meraki_device_payload_0f_b_n2h/ansible_meraki_device_payload.zip/ansible/module_utils/network/meraki/meraki.py", line 92, in inner
ansible.module_utils.network.meraki.meraki.HTTPError: HTTP error 400 - None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/peter/.ansible/tmp/ansible-tmp-1592480055.1857505-281351811665172/AnsiballZ_meraki_device.py", line 102, in <module>
    _ansiballz_main()
  File "/home/peter/.ansible/tmp/ansible-tmp-1592480055.1857505-281351811665172/AnsiballZ_meraki_device.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/peter/.ansible/tmp/ansible-tmp-1592480055.1857505-281351811665172/AnsiballZ_meraki_device.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.meraki.meraki_device', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_meraki_device_payload_0f_b_n2h/ansible_meraki_device_payload.zip/ansible/modules/network/meraki/meraki_device.py", line 430, in <module>
  File "/tmp/ansible_meraki_device_payload_0f_b_n2h/ansible_meraki_device_payload.zip/ansible/modules/network/meraki/meraki_device.py", line 388, in main
  File "/tmp/ansible_meraki_device_payload_0f_b_n2h/ansible_meraki_device_payload.zip/ansible/module_utils/network/meraki/meraki.py", line 116, in inner
ansible.module_utils.network.meraki.meraki.HTTPError: HTTP error 400 - None
Trying secret FileVaultSecret(filename='/home/peter/repositories/ansible/vault_password') for vault_id=default
failed: [localhost] (REMOVED SENSITIVE INFO) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": [
        (REMOVED SENSITIVE INFO)
    ],
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_meraki_device_payload_0f_b_n2h/ansible_meraki_device_payload.zip/ansible/module_utils/network/meraki/meraki.py\", line 92, in inner\nansible.module_utils.network.meraki.meraki.HTTPError: HTTP error 400 - None\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/peter/.ansible/tmp/ansible-tmp-1592480055.1857505-281351811665172/AnsiballZ_meraki_device.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/peter/.ansible/tmp/ansible-tmp-1592480055.1857505-281351811665172/AnsiballZ_meraki_device.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/peter/.ansible/tmp/ansible-tmp-1592480055.1857505-281351811665172/AnsiballZ_meraki_device.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.meraki.meraki_device', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_meraki_device_payload_0f_b_n2h/ansible_meraki_device_payload.zip/ansible/modules/network/meraki/meraki_device.py\", line 430, in <module>\n  File \"/tmp/ansible_meraki_device_payload_0f_b_n2h/ansible_meraki_device_payload.zip/ansible/modules/network/meraki/meraki_device.py\", line 388, in main\n  File \"/tmp/ansible_meraki_device_payload_0f_b_n2h/ansible_meraki_device_payload.zip/ansible/module_utils/network/meraki/meraki.py\", line 116, in inner\nansible.module_utils.network.meraki.meraki.HTTPError: HTTP error 400 - None\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by kbreit** [comment]
@petertavenier Thank you for the bug report. Give me a little time to look into this and I'll let you know what I find.

**Comment by kbreit** [comment]
@petertavenier I ran the integration test and it worked, but that doesn't mean everything is good. I'd like to start with a few basics. What version of Ansible are you using and are you using the Meraki collection?

**Comment by petertavenier** [comment]
@kbreit The integration test is [this file](https://github.com/CiscoDevNet/ansible-meraki/blob/master/tests/integration/targets/meraki_device/tasks/main.yml) is suppose? I already looked into this playbook, but only the `state: query` is used in combination with hostname. `hostname: "bla-bla-device"` is *not* used together with `state: present`.

**Comment by kbreit** [comment]
I have an alias for `hostname` of `name` and there is a task which uses `name`. https://github.com/CiscoDevNet/ansible-meraki/blob/d3a15a9ceebfd5a30b8f2bad13e4a89124f3e02d/tests/integration/targets/meraki_device/tasks/main.yml#L163

Does this task generally match what you're looking for?

**Comment by kbreit** [comment]
I've done a little more testing and definitely have seen some quirks with how it acts. It's not crashing like it is for you but it's also not applying the hostname if I'm just applying hostname. I will troubleshoot this but consider the bug confirmed.

**Comment by kbreit** [comment]
@petertavenier I created a pull request to fix this bug tonight. https://github.com/CiscoDevNet/ansible-meraki/pull/101 is what you should try but see if you can do it against a test environment and not production. This is a pretty large rewrite of the module and I don't know if I'm missing corner cases. Overall this is a more straight forward code base but still may not be right or have bugs I haven't found.

**Comment by petertavenier** [comment]
I tested it see comment in #101
